version: 2.1

executors:
  android:
    docker:
      - image: circleci/android:latest
    working_directory: ~/project

jobs:
  build:
    executor: android
    steps:
      - checkout
      - run:
          name: Install JDK 17
          command: |
            sudo apt-get update
            sudo apt-get install -y wget
            wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb
            sudo apt-get install -y ./jdk-17_linux-x64_bin.deb
            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-17/bin/java 1
            sudo update-alternatives --set java /usr/lib/jvm/jdk-17/bin/java
            java -version
      - run:
          name: Build Project
          command: ./gradlew build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
