version: 2.1

executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'

orbs:
  android: circleci/android@2.1.2
  maven: circleci/maven@1.3.0

jobs:
  release-build:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk

workflows:
  maven_test:
    jobs:
      - maven/test:
          command: '-X compile'
          executor: java17
  test-and-build:
    jobs:
      - release-build:
          filters:
            branches:
              only: master
