version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  release-build:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk

workflows:
  test-and-build:
    jobs:
      - release-build:
          filters:
            branches:
              only: master
